Repository flovouin/terraform-provider-metabase, pull requests merged in 2024-04, with the labels that each got.

#45 ✅ Test the `metabase_table` resource
  internal/provider/table_resource_test.go
Labels: chore

#47 🔖 Prepare v0.5.0
  CHANGELOG.md
  README.md
Labels: chore

#49 🔨 Fix bug for Metabase Pro instances with modified analytics permissions
  internal/provider/permissions_graph_resource.go
  metabase-api.yaml
  metabase/client.gen.go
  metabase/utils.go
Labels: bug

#50 🔖 Prepare v0.5.1
  CHANGELOG.md
  README.md
Labels: chore

#54 ✨ Dashboard filtering parameters (linking filters)
  CHANGELOG.md
  internal/provider/dashboard_resource_test.go
  metabase-api.yaml
  metabase/client.gen.go
Labels: feature, metabase_dashboard

#55 🔖 Prepare v0.6.0
  CHANGELOG.md
Labels: chore
